apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: report-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: report
  labels:
    app: report
spec:
  selector:
    matchLabels:
      app: report 
  template:
    metadata:
      labels:
        app: report
    spec:
      volumes:
        - name: report-volume
          persistentVolumeClaim:
            claimName: report-volume
      containers:
        - image: nginx:latest
          name: report-nginx
          volumeMounts:
          - name: report-volume
            mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  name: report-service
  labels:
    app: report-service
spec:
  ports:
    - port: 80 
      protocol: TCP
      targetPort: 80 
  selector:
    app: report
