apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: freedomknight/simplestress-server:latest
          name: grpc-server
          imagePullPolicy: "Always"

---

kind: Service
apiVersion: v1
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051 
  selector:
    app: api

