// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: proto/paddle.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Paddle_Serve_FullMethodName = "/proto.Paddle/Serve"
)

// PaddleClient is the client API for Paddle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaddleClient interface {
	Serve(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
}

type paddleClient struct {
	cc grpc.ClientConnInterface
}

func NewPaddleClient(cc grpc.ClientConnInterface) PaddleClient {
	return &paddleClient{cc}
}

func (c *paddleClient) Serve(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, Paddle_Serve_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaddleServer is the server API for Paddle service.
// All implementations must embed UnimplementedPaddleServer
// for forward compatibility
type PaddleServer interface {
	Serve(context.Context, *Ping) (*Pong, error)
	mustEmbedUnimplementedPaddleServer()
}

// UnimplementedPaddleServer must be embedded to have forward compatible implementations.
type UnimplementedPaddleServer struct {
}

func (UnimplementedPaddleServer) Serve(context.Context, *Ping) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Serve not implemented")
}
func (UnimplementedPaddleServer) mustEmbedUnimplementedPaddleServer() {}

// UnsafePaddleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaddleServer will
// result in compilation errors.
type UnsafePaddleServer interface {
	mustEmbedUnimplementedPaddleServer()
}

func RegisterPaddleServer(s grpc.ServiceRegistrar, srv PaddleServer) {
	s.RegisterService(&Paddle_ServiceDesc, srv)
}

func _Paddle_Serve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaddleServer).Serve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paddle_Serve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaddleServer).Serve(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

// Paddle_ServiceDesc is the grpc.ServiceDesc for Paddle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Paddle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Paddle",
	HandlerType: (*PaddleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Serve",
			Handler:    _Paddle_Serve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paddle.proto",
}
